### ISSUE TITLE
gradle导入的时候报错

### ISSUE THREAD

**Issue by tx123456** [hpdx/fresco-photoview#1]
Error:(60, 13) Failed to resolve: com.facebook.fresco.helper:fresco-photoview:1.1.8
<a href="openFile:E:/Studio work/AiGuiQuan/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:(61, 13) Failed to resolve: com.facebook.fresco.helper:fresco-helper:1.2.2
<a href="openFile:E:/Studio work/AiGuiQuan/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: annotationProcessor
<a href="openFile:E:/Studio work/AiGuiQuan/app/build.gradle">Open File</a>

gradle导入直接保存，该怎么解决

**Comment by hpdx** [comment]
@tx123456 需要添加下面的配置：
 maven {
            url 'https://dl.bintray.com/hpdx/maven/'
        }
